num1 = float(input("Digite o primeiro número: "))
num2 = float(input("Digite o segundo número: "))
num3 = float(input("Digite o terceiro número: "))
numeros = sorted([num1, num2, num3])
print(f"Números em ordem crescente: {numeros}")
